# --- !Ups

CREATE TABLE "SUPERHERO" ("NAME" VARCHAR NOT NULL PRIMARY KEY, "PASSWORT" VARCHAR);
CREATE TABLE "HEROBODY" ("NAME" VARCHAR NOT NULL PRIMARY KEY ,FOREIGN KEY("NAME") REFERENCES "SUPERHERO"("NAME"), "HEALTHMAX" INT, "HEALTHCURRENT" INT,  "DEFENSE" INT,  "ATTACK" INT,  "MANAMAX" INT, "MANACURRENT" INT, "STATPOINTS" INT);
CREATE TABLE "HEROABILITY" ("NAME" VARCHAR NOT NULL PRIMARY KEY ,FOREIGN KEY("NAME") REFERENCES "SUPERHERO"("NAME"), "FIRSTABILITY" VARCHAR NOT NULL, "SECONDABILITY" VARCHAR NOT NULL, "THIRDABILITY" VARCHAR NOT NULL);
# --- !Downs

DROP TABLE "SUPERHERO";
DROP TABLE "HEROBODY"